let Teste: {
  acquirer_reconciliation: [],
  additional_info: {
    available_balance: null,
    ip_address: '168.205.129.160',
    nsu_processadora: null,
    payer: { first_name: 'Rafael Batista Santos' }
  },
  authorization_code: null,
  binary_mode: true,
  brand_id: null,
  call_for_authorize_id: null,
  captured: true,
  card: {
    cardholder: { identification: [Object], name: 'APRO' },
    date_created: '2021-05-19T00:10:16.000-04:00',
    date_last_updated: '2021-05-19T00:10:16.000-04:00',
    expiration_month: 11,
    expiration_year: 2025,
    first_six_digits: '503143',
    id: null,
    last_four_digits: '6351'
  },
  charges_details: [],
  collector_id: 757039068,
  corporation_id: null,
  counter_currency: null,
  coupon_amount: 0,
  currency_id: 'BRL',
  date_approved: '2021-05-19T00:10:16.263-04:00',
  date_created: '2021-05-19T00:10:16.126-04:00',
  date_last_updated: '2021-05-19T00:10:16.263-04:00',
  date_of_expiration: null,
  deduction_schema: null,
  description: 'Curso de Anatomia',
  differential_pricing_id: null,
  external_reference: '08420698440',
  fee_details: [{ amount: 0.05, fee_payer: 'collector', type: 'mercadopago_fee' }],
  id: 1236919975,
  installments: 1,
  integrator_id: null,
  issuer_id: '24',
  live_mode: false,
  marketplace_owner: null,
  merchant_account_id: null,
  merchant_number: null,
  metadata: {},
  money_release_date: '2021-05-19T00:10:16.263-04:00',
  money_release_schema: null,
  notification_url: 'https://bot2.rj2.app/api/v1/mercadopago/notification',
  operation_type: 'regular_payment',
  order: { id: '2694553233', type: 'mercadopago' },
  payer: {
    first_name: null,
    last_name: null,
    email: 'test_user_80507629@testuser.com',
    identification: { number: '32659430', type: 'DNI' },
    phone: { area_code: null, number: null, extension: null },
    type: null,
    entity_type: null,
    id: '168948207'
  },
  payment_method_id: 'master',
  payment_type_id: 'credit_card',
  platform_id: null,
  point_of_interaction: {},
  pos_id: null,
  processing_mode: 'aggregator',
  refunds: [],
  shipping_amount: 0,
  sponsor_id: null,
  statement_descriptor: 'CLUBEDAANATOM',
  status: 'approved',
  status_detail: 'accredited',
  store_id: null,
  taxes_amount: 0,
  transaction_amount: 1,
  transaction_amount_refunded: 0,
  transaction_details: {
    acquirer_reference: null,
    external_resource_url: null,
    financial_institution: null,
    installment_amount: 1,
    net_received_amount: 0.95,
    overpaid_amount: 0,
    payable_deferral_period: null,
    payment_method_reference_id: null,
    total_paid_amount: 1
  }
}
